### ISSUE TITLE
ppaste not work with jpg file?

### ISSUE THREAD

**Issue by JarvistFth** [binwiederhier/pcopy#80]
hi~ i think this is an awesome project .

but when i tried to paste some jpg images via https://nopaste.net/  something wrong occured.

steps:
1. follow the docker usage instruction.
`docker pull binwiederhier/pcopy
alias pcopy="docker run --rm -v ~/.cache/pcopy:/var/cache/pcopy -v ~/.config/pcopy:/etc/pcopy -p 2586:2586/tcp -it binwiederhier/pcopy"
alias pcp="pcopy copy"
alias ppaste="pcopy paste"`
2. do `pcopy join nopaste.net` 
3. go to https://nopaste.net/ and drag my jpg image to it
4. do `ppaste XXXXXXXX > xx.jpg`

then it seems the file is broken. but i use curl that's ok.

**Comment by binwiederhier** [comment]
That is super odd. I'll look at this later today.

**Comment by binwiederhier** [comment]
Wait, did you join and upload the image to nopaste.net or your docker's IP address? The nopaste.net instance has pretty strict limits. Your example talks about nopaste.net AND the docker image. That doesn't quite adds up.

**Comment by JarvistFth** [comment]
> 

yeah, i use binaries that's ok. i think i was mixed up between them.. thx ..
T_T..

**Comment by JarvistFth** [comment]
> yeah, i use binaries that's ok. i think i was mixed up between them.. thx ..
> T_T..



> Wait, did you join and upload the image to nopaste.net or your docker's IP address? The nopaste.net instance has pretty strict limits. Your example talks about nopaste.net AND the docker image. That doesn't quite adds up.

yeah, i use binaries that's ok. i think i was mixed up between them.. thx ..
T_T..

**Comment by binwiederhier** [comment]
So I assume this can be closed? Please reopen if you're still having issues.
